services:
  - type: web
    name: arweave-block-explorer
    runtime: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
